reset ((control h -> 3 * (h 2)) + (control g -> (fun x -> x + 1) (g 4)))

(* left-to-right *)
(* < (Fh. 3 * h 2) + (Fg. (\x. x + 1) (g 4)) > *)
(* < 3 * h 2 > where h = \x. x + (Fg. (\x. x + 1) (g 4)) *)
(* < 3 * (2 + (Fg. (\x. x + 1) (g 4))) > *)
(* < (\x. x + 1) (g 4) > where g = \x. 3 * (2 + x) *)
(* < (\x. x + 1) (3 * (2 + 4)) > *)
(* 19 *)

(* right-to-left *)
(* < (Fh. 3 * h 2) + (Fg. (\x. x + 1) (g 4)) > *)
(* < (\x. x + 1) (g 4) > where g = \x. (Fh. 3 * h 2) + x *)
(* < (\x. x + 1) ((Fh. 3 * h 2) + 4) > *)
(* < 3 * h 2 > where h = \x. (\x. x + 1) (x + 4) *)
(* < 3 * (\x. x + 1) (2 + 4) > *)
(* 21 *)
