reset ((control h -> 1 + (h 2)) + (control g -> (fun x -> x * 3) (g 4)))

(* left-to-right *)
(* < (Fh. 1 + h 2) + (Fg. (\x. x * 3) (g 4)) > *)
(* < 1 + h 2 > where h = \x. x + (Fg. (\x. x * 3) (g 4)) *)
(* < 1 + (2 + (Fg. (\x. x * 3) (g 4))) > *)
(* < (\x. x * 3) (g 4) > where g = \x. 1 + (2 + x) *)
(* < (\x. x * 3) (1 + (2 + 4)) > *)
(* 21 *)

(* right-to-left *)
(* < (Fh. 1 + h 2) + (Fg. (\x. x * 3) (g 4)) > *)
(* < (\x. x * 3) (g 4) > where g = \x. (Fh. 1 + h 2) + x *)
(* < (\x. x * 3) ((Fh. 1 + h 2) + 4) > *)
(* < 1 + h 2 > where h = \x. (\x. x * 3) (x + 4) *)
(* < 1 + (\x. x * 3) (2 + 4) > *)
(* 19 *)
